/**
 * Hand-authored pixel-art picture library for the Nonogram game.
 *
 * Each pattern is a square grid drawn as text rows so it stays readable and
 * editable here: `#` is a filled cell, any other character (`.`) is empty. The
 * game derives the row/column clues from the grid (see `nonogramFromPattern`),
 * so every pattern is trivially solvable — its own picture is a valid solution.
 *
 * Patterns are grouped by side length so the picker can offer only the ones
 * that fit the current board size. Fully self-contained — no network.
 *
 * Design note: mirror-symmetric pictures make for weak puzzles (the clues
 * mirror too, so half the deduction is free), so symmetry is allowed only on
 * the easy 5×5 boards; the 10×10 and 15×15 pictures are deliberately
 * asymmetric.
 */
import type { NonogramPattern } from './nonogram'
import { rngFromSeed } from './seed'

/** 5×5 pictures — bold, single-glance shapes (symmetry is fine at easy size). */
const P5: NonogramPattern[] = [
  {
    id: 'heart5',
    name: 'Heart',
    size: 5,
    rows: [
      '.#.#.',
      '#####',
      '#####',
      '.###.',
      '..#..',
    ],
  },
  {
    id: 'diamond5',
    name: 'Diamond',
    size: 5,
    rows: [
      '..#..',
      '.###.',
      '#####',
      '.###.',
      '..#..',
    ],
  },
  {
    id: 'plus5',
    name: 'Plus',
    size: 5,
    rows: [
      '..#..',
      '..#..',
      '#####',
      '..#..',
      '..#..',
    ],
  },
  {
    id: 'boat5',
    name: 'Boat',
    size: 5,
    rows: [
      '..#..',
      '..##.',
      '#####',
      '.###.',
      '.....',
    ],
  },
  {
    id: 'key5',
    name: 'Key',
    size: 5,
    rows: [
      '.###.',
      '.#.#.',
      '.###.',
      '..#..',
      '..##.',
    ],
  },
  {
    id: 'tree5',
    name: 'Tree',
    size: 5,
    rows: [
      '..#..',
      '.###.',
      '#####',
      '..#..',
      '..#..',
    ],
  },
  {
    id: 'cup5',
    name: 'Cup',
    size: 5,
    rows: [
      '####.',
      '#..##',
      '#..##',
      '####.',
      '.....',
    ],
  },
]

/** 10×10 pictures — deliberately asymmetric so the clues stay interesting. */
const P10: NonogramPattern[] = [
  {
    id: 'duck10',
    name: 'Duck',
    size: 10,
    rows: [
      '...###....',
      '..#####...',
      '..#######.',
      '...####...',
      '#...####..',
      '##.######.',
      '#########.',
      '.########.',
      '..######..',
      '..........',
    ],
  },
  {
    id: 'sailboat10',
    name: 'Sailboat',
    size: 10,
    rows: [
      '....#.....',
      '....##....',
      '....###...',
      '....####..',
      '....#####.',
      '....#.....',
      '##########',
      '.########.',
      '..######..',
      '..........',
    ],
  },
  {
    id: 'cat10',
    name: 'Cat',
    size: 10,
    rows: [
      '.#...#....',
      '.##.##....',
      '.#####....',
      '.#####....',
      '..###.....',
      '..####...#',
      '.######..#',
      '.#######.#',
      '.########.',
      '..........',
    ],
  },
  {
    id: 'dog10',
    name: 'Dog',
    size: 10,
    rows: [
      '.##.......',
      '.###.....#',
      '.#########',
      '..########',
      '..######..',
      '..######..',
      '..##..##..',
      '..##..##..',
      '..........',
      '..........',
    ],
  },
  {
    id: 'mug10',
    name: 'Mug',
    size: 10,
    rows: [
      '..........',
      '.######...',
      '.########.',
      '.######.#.',
      '.######.#.',
      '.########.',
      '.######...',
      '..####....',
      '..........',
      '..........',
    ],
  },
  {
    id: 'snail10',
    name: 'Snail',
    size: 10,
    rows: [
      '.......#.#',
      '........##',
      '..####..##',
      '.######.##',
      '.##..##.##',
      '.##.#.#.##',
      '.######.##',
      '..####..##',
      '##########',
      '..........',
    ],
  },
  {
    id: 'fish10',
    name: 'Fish',
    size: 10,
    rows: [
      '..........',
      '...####..#',
      '..########',
      '.##.######',
      '..########',
      '...####..#',
      '..........',
      '..........',
      '..........',
      '..........',
    ],
  },
  {
    id: 'house10',
    name: 'House',
    size: 10,
    rows: [
      '....#..#..',
      '...###.#..',
      '..######..',
      '.########.',
      '.########.',
      '.########.',
      '.####..##.',
      '.####..##.',
      '.####..##.',
      '..........',
    ],
  },
  {
    id: 'umbrella10',
    name: 'Umbrella',
    size: 10,
    rows: [
      '...####...',
      '.########.',
      '##########',
      '.....#....',
      '.....#....',
      '.....#....',
      '.....#....',
      '.#...#....',
      '.##.##....',
      '..###.....',
    ],
  },
  {
    id: 'note10',
    name: 'Music Note',
    size: 10,
    rows: [
      '...######.',
      '...#....#.',
      '...#....#.',
      '...#....#.',
      '...#....#.',
      '.###..###.',
      '####..####',
      '.##....##.',
      '..........',
      '..........',
    ],
  },
]

/** 15×15 pictures — bigger scenes, all asymmetric. */
const P15: NonogramPattern[] = [
  {
    id: 'sailboat15',
    name: 'Sailboat',
    size: 15,
    rows: [
      '.......#.......',
      '.......##......',
      '.......###.....',
      '.......####....',
      '..#....#####...',
      '..##...######..',
      '..###..#######.',
      '..####.#######.',
      '.......#.......',
      '###############',
      '.#############.',
      '..###########..',
      '...............',
      '...............',
      '...............',
    ],
  },
  {
    id: 'trex15',
    name: 'T-Rex',
    size: 15,
    rows: [
      '...####........',
      '..######.......',
      '..#.####.......',
      '..#######......',
      '..#####........',
      '....####.......',
      '....#####....##',
      '....#######.##.',
      '...##########..',
      '...#########...',
      '....########...',
      '....##..##.....',
      '....##..##.....',
      '...###...##....',
      '...............',
    ],
  },
  {
    id: 'teapot15',
    name: 'Teapot',
    size: 15,
    rows: [
      '.......##......',
      '.....######....',
      '....########...',
      '....##########.',
      '.#..########.#.',
      '.##.########.#.',
      '.###########.#.',
      '....########.#.',
      '....##########.',
      '.....########..',
      '......######...',
      '...............',
      '...............',
      '...............',
      '...............',
    ],
  },
  {
    id: 'guitar15',
    name: 'Guitar',
    size: 15,
    rows: [
      '...........##..',
      '..........##...',
      '.........##....',
      '.........##....',
      '.........##....',
      '........####...',
      '.......######..',
      '......########.',
      '......########.',
      '......###..###.',
      '......###..###.',
      '......########.',
      '.......######..',
      '........####...',
      '...............',
    ],
  },
  {
    id: 'toucan15',
    name: 'Toucan',
    size: 15,
    rows: [
      '......#####....',
      '.....#######...',
      '.....##.#####..',
      '#############..',
      '..###########..',
      '.....########..',
      '.....########..',
      '......######...',
      '......#######..',
      '.......##..###.',
      '............##.',
      '.............#.',
      '...............',
      '...............',
      '...............',
    ],
  },
  {
    id: 'castle15',
    name: 'Castle',
    size: 15,
    rows: [
      '.#.............',
      '.###...........',
      '.#.............',
      '#.#.#..........',
      '#####..........',
      '#####..........',
      '#####..#.#.#.#.',
      '#####..########',
      '###############',
      '###############',
      '######...######',
      '######...######',
      '...............',
      '...............',
      '...............',
    ],
  },
  {
    id: 'cactus15',
    name: 'Cactus',
    size: 15,
    rows: [
      '......##.......',
      '.....####......',
      '.....####......',
      '.....####..##..',
      '.##..####..##..',
      '.##..####..##..',
      '.##..####..##..',
      '.##..########..',
      '.########......',
      '.....####......',
      '.....####......',
      '.....####......',
      '....######.....',
      '.....####......',
      '...............',
    ],
  },
]

/**
 * Retired pictures — removed from the picker and the random pool (too
 * symmetric outside easy mode), but kept loadable by id so shared URLs from
 * before the library rework (e.g. /nonogram/10.@heart10) still open the exact
 * picture they were solved on.
 */
const LEGACY: NonogramPattern[] = [
  {
    id: 'x5',
    name: 'Cross X',
    size: 5,
    legacy: true,
    rows: [
      '#...#',
      '.#.#.',
      '..#..',
      '.#.#.',
      '#...#',
    ],
  },
  {
    id: 'heart10',
    name: 'Heart',
    size: 10,
    legacy: true,
    rows: [
      '..........',
      '.##....##.',
      '##########',
      '##########',
      '##########',
      '.########.',
      '..######..',
      '...####...',
      '....##....',
      '..........',
    ],
  },
  {
    id: 'invader10',
    name: 'Space Invader',
    size: 10,
    legacy: true,
    rows: [
      '..........',
      '..#....#..',
      '...#..#...',
      '..######..',
      '.##.##.##.',
      '##########',
      '#.######.#',
      '#.#....#.#',
      '...#..#...',
      '..#....#..',
    ],
  },
  {
    id: 'plus10',
    name: 'Plus',
    size: 10,
    legacy: true,
    rows: [
      '....##....',
      '....##....',
      '....##....',
      '....##....',
      '##########',
      '##########',
      '....##....',
      '....##....',
      '....##....',
      '....##....',
    ],
  },
  {
    id: 'smiley10',
    name: 'Smiley',
    size: 10,
    legacy: true,
    rows: [
      '..######..',
      '.########.',
      '###.##.###',
      '###.##.###',
      '##########',
      '##########',
      '#.######.#',
      '##.####.##',
      '.########.',
      '..######..',
    ],
  },
  {
    id: 'heart15',
    name: 'Heart',
    size: 15,
    legacy: true,
    rows: [
      '...............',
      '..###.....###..',
      '.#####...#####.',
      '.#############.',
      '.#############.',
      '.#############.',
      '.#############.',
      '..###########..',
      '...#########...',
      '....#######....',
      '.....#####.....',
      '......###......',
      '.......#.......',
      '...............',
      '...............',
    ],
  },
  {
    id: 'diamond15',
    name: 'Diamond',
    size: 15,
    legacy: true,
    rows: [
      '.......#.......',
      '......###......',
      '.....#####.....',
      '....#######....',
      '...#########...',
      '..###########..',
      '.#############.',
      '###############',
      '.#############.',
      '..###########..',
      '...#########...',
      '....#######....',
      '.....#####.....',
      '......###......',
      '.......#.......',
    ],
  },
  {
    id: 'mushroom15',
    name: 'Mushroom',
    size: 15,
    legacy: true,
    rows: [
      '...............',
      '....#######....',
      '..###########..',
      '.#############.',
      '###############',
      '###############',
      '.#############.',
      '..###########..',
      '.....#####.....',
      '.....#####.....',
      '.....#####.....',
      '.....#####.....',
      '....#######....',
      '....#######....',
      '...............',
    ],
  },
  {
    id: 'invader15',
    name: 'Space Invader',
    size: 15,
    legacy: true,
    rows: [
      '...............',
      '...............',
      '...............',
      '....#.....#....',
      '.....#...#.....',
      '....#######....',
      '...##.###.##...',
      '..###########..',
      '..#.#######.#..',
      '..#.#.....#.#..',
      '.....##.##.....',
      '...............',
      '...............',
      '...............',
      '...............',
    ],
  },
]

/** All bundled pictures, across every supported board size (legacy included). */
export const NONOGRAM_PATTERNS: NonogramPattern[] = [...P5, ...P10, ...P15, ...LEGACY]

/** Pictures offered for a given square board size (legacy stays URL-only). */
export const patternsForSize = (size: number): NonogramPattern[] =>
  NONOGRAM_PATTERNS.filter((p) => p.size === size && !p.legacy)

/** Look up a picture by its id (optionally constrained to a board size). */
export const patternById = (id: string, size?: number): NonogramPattern | undefined =>
  NONOGRAM_PATTERNS.find((p) => p.id === id && (size === undefined || p.size === size))

/**
 * Deterministically pick one picture that fits `size`, chosen by `seed`. Used
 * for the default / "Random" puzzle so it is always a recognisable picture (not
 * random noise) while staying shareable — the same seed reproduces the same one.
 */
export const randomPatternForSize = (
  size: number,
  seed: string,
): NonogramPattern | undefined => {
  const options = patternsForSize(size)
  if (!options.length) return undefined
  const i = Math.floor(rngFromSeed(`nono-pick:${size}:${seed}`)() * options.length)
  return options[Math.min(i, options.length - 1)]
}
